version: '3'
services: 
  db: 
    image: postgres
    restart: always
    volumes:
      - .data/db:/var/lib/postgres/data
    ports:
      - 5432:5432
    
    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=testpostgres
      - POSTGRES_PASSWORD=testpostgres